// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331041551_AddSprintDescriptions")]
    partial class AddSprintDescriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CongNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NhomKyNangId")
                        .HasColumnType("int");

                    b.Property<string>("TenCongNghe")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("NhomKyNangId");

                    b.ToTable("CongNghes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AiMatchScore")
                        .HasColumnType("float");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DoUuTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiCongViec")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDauDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayBatDauThucTe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucThucTe")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucGiaoViec")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLanBiTuChoi")
                        .HasColumnType("int");

                    b.Property<int?>("SprintId")
                        .HasColumnType("int");

                    b.Property<double?>("ThoiGianThucTe")
                        .HasColumnType("float");

                    b.Property<double>("ThoiGianUocTinh")
                        .HasColumnType("float");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ViTri")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DuAnId");

                    b.HasIndex("SprintId");

                    b.ToTable("CongViecs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DuAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDuAn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("DuAns", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DuAnNguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JointAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DuAnId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("DuAnNguoiDungs");
                });

            modelBuilder.Entity("Domain.Entities.KyNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CongNgheId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKyNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CongNgheId");

                    b.ToTable("KyNangs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KyNangNguoiDung", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("KyNangId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("int");

                    b.HasKey("UserId", "KyNangId");

                    b.HasIndex("KyNangId");

                    b.ToTable("KyNangNguoiDungs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NguoiDungVaiTro", b =>
                {
                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("NguoiDungId", "VaiTroId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDungVaiTros");
                });

            modelBuilder.Entity("Domain.Entities.NhatKyCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CongViecId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiCapNhatId")
                        .HasColumnType("int");

                    b.Property<double>("SoGioLamViec")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CongViecId");

                    b.HasIndex("NguoiCapNhatId");

                    b.ToTable("NhatKyCongViecs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NhomKyNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("NhomKyNangs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NhomQuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhomQuyens");
                });

            modelBuilder.Entity("Domain.Entities.PhuThuocCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DependsOnTaskId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("PhuThuocCongViecs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.QuyTacGiaoViecAI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiDuLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaQuyTac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyTac")
                        .IsUnique();

                    b.ToTable("QuyTacGiaoViecAIs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NhomQuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.HasIndex("NhomQuyenId");

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("Domain.Entities.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSprint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DuAnId");

                    b.ToTable("Sprints", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TaiLieuDuAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DuAnId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DuAnId");

                    b.ToTable("TaiLieuDuAns", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("Domain.Entities.TraoLoiCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CongViecId")
                        .HasColumnType("int");

                    b.Property<int?>("CongViecId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CongViecId");

                    b.HasIndex("CongViecId1");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("TraoLoiCongViecs");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("KhoiLuongCongViec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("Domain.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTroQuyens");
                });

            modelBuilder.Entity("Domain.Entities.YeuCauCongViec", b =>
                {
                    b.Property<int>("CongViecId")
                        .HasColumnType("int");

                    b.Property<int>("KyNangId")
                        .HasColumnType("int");

                    b.Property<int>("MucDoYeuCau")
                        .HasColumnType("int");

                    b.HasKey("CongViecId", "KyNangId");

                    b.HasIndex("KyNangId");

                    b.ToTable("YeuCauCongViecs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CongNghe", b =>
                {
                    b.HasOne("Domain.Entities.NhomKyNang", "NhomKyNang")
                        .WithMany("CongNghes")
                        .HasForeignKey("NhomKyNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomKyNang");
                });

            modelBuilder.Entity("Domain.Entities.CongViec", b =>
                {
                    b.HasOne("Domain.Entities.User", "Assignee")
                        .WithMany("CongViecs")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.DuAn", "DuAn")
                        .WithMany("CongViecs")
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sprint", "Sprint")
                        .WithMany("CongViecs")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Assignee");

                    b.Navigation("Creator");

                    b.Navigation("DuAn");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Domain.Entities.DuAn", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Entities.DuAnNguoiDung", b =>
                {
                    b.HasOne("Domain.Entities.DuAn", "DuAn")
                        .WithMany("DuAnNguoiDungs")
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "NguoiDung")
                        .WithMany("DuAnNguoiDungs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Domain.Entities.KyNang", b =>
                {
                    b.HasOne("Domain.Entities.CongNghe", "CongNghe")
                        .WithMany("KyNangs")
                        .HasForeignKey("CongNgheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongNghe");
                });

            modelBuilder.Entity("Domain.Entities.KyNangNguoiDung", b =>
                {
                    b.HasOne("Domain.Entities.KyNang", "KyNang")
                        .WithMany("KyNangNguoiDungs")
                        .HasForeignKey("KyNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("KyNangNguoiDungs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.NguoiDungVaiTro", b =>
                {
                    b.HasOne("Domain.Entities.User", "NguoiDung")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Domain.Entities.NhatKyCongViec", b =>
                {
                    b.HasOne("Domain.Entities.CongViec", "CongViec")
                        .WithMany()
                        .HasForeignKey("CongViecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "NguoiCapNhat")
                        .WithMany()
                        .HasForeignKey("NguoiCapNhatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("NguoiCapNhat");
                });

            modelBuilder.Entity("Domain.Entities.PhuThuocCongViec", b =>
                {
                    b.HasOne("Domain.Entities.CongViec", "DependsOnTask")
                        .WithMany()
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CongViec", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Domain.Entities.Quyen", b =>
                {
                    b.HasOne("Domain.Entities.NhomQuyen", "NhomQuyen")
                        .WithMany("Quyens")
                        .HasForeignKey("NhomQuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomQuyen");
                });

            modelBuilder.Entity("Domain.Entities.Sprint", b =>
                {
                    b.HasOne("Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.DuAn", "DuAn")
                        .WithMany("Sprints")
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("Domain.Entities.TaiLieuDuAn", b =>
                {
                    b.HasOne("Domain.Entities.DuAn", "DuAn")
                        .WithMany("TaiLieuDuAns")
                        .HasForeignKey("DuAnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");
                });

            modelBuilder.Entity("Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("Domain.Entities.DuAn", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TraoLoiCongViec", b =>
                {
                    b.HasOne("Domain.Entities.CongViec", "CongViec")
                        .WithMany()
                        .HasForeignKey("CongViecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CongViec", null)
                        .WithMany("TraoLoiCongViecs")
                        .HasForeignKey("CongViecId1");

                    b.HasOne("Domain.Entities.User", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("Domain.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("Domain.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("Domain.Entities.YeuCauCongViec", b =>
                {
                    b.HasOne("Domain.Entities.CongViec", "CongViec")
                        .WithMany("YeuCauCongViecs")
                        .HasForeignKey("CongViecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.KyNang", "KyNang")
                        .WithMany("YeuCauCongViecs")
                        .HasForeignKey("KyNangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CongViec");

                    b.Navigation("KyNang");
                });

            modelBuilder.Entity("Domain.Entities.CongNghe", b =>
                {
                    b.Navigation("KyNangs");
                });

            modelBuilder.Entity("Domain.Entities.CongViec", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("TraoLoiCongViecs");

                    b.Navigation("YeuCauCongViecs");
                });

            modelBuilder.Entity("Domain.Entities.DuAn", b =>
                {
                    b.Navigation("CongViecs");

                    b.Navigation("DuAnNguoiDungs");

                    b.Navigation("Sprints");

                    b.Navigation("TaiLieuDuAns");
                });

            modelBuilder.Entity("Domain.Entities.KyNang", b =>
                {
                    b.Navigation("KyNangNguoiDungs");

                    b.Navigation("YeuCauCongViecs");
                });

            modelBuilder.Entity("Domain.Entities.NhomKyNang", b =>
                {
                    b.Navigation("CongNghes");
                });

            modelBuilder.Entity("Domain.Entities.NhomQuyen", b =>
                {
                    b.Navigation("Quyens");
                });

            modelBuilder.Entity("Domain.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("Domain.Entities.Sprint", b =>
                {
                    b.Navigation("CongViecs");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("CongViecs");

                    b.Navigation("DuAnNguoiDungs");

                    b.Navigation("KyNangNguoiDungs");

                    b.Navigation("NguoiDungVaiTros");
                });

            modelBuilder.Entity("Domain.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungVaiTros");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
